### PR TITLE
Improved Mixin code assistance

### PR DESCRIPTION
**Pull request by Minecrell**
These changes extend MinecraftDev with a lot of utilities for working with Mixins:

- **Automatic completion of `@Shadow` members:** Members in the target class are available like regular fields in the code completion of the Mixin class. If selected, a `@Shadow` member will be generated automatically.
- Code completion + inspection for method reference in `@Inject`, `@ModifyArg`, `@ModifyConstant`, `@ModifyVariable` and `@Redirect`, as well as injection point types
- "Generate `@Overwrite`" action: Copies the original method source and adds all necessary `@Shadow` members
- "Generate `@Shadow`" action: Generates a `@Shadow` member for a selected member in the target class
- `@Overwrite` inspection and line markers (to verify that the target method actually exists)
- Improved handling of copy/paste from the target class, will automatically add all necessary `@Shadow` elements when copying code from the target class
- Inspection for `@Inject` method signatures ("should be (not) static" and method parameters)
- Fix for #102 - allow references to Mixins if they are part of the hierarchy
- Static member inspection now ignores `@Shadow` members
- "Copy Mixin target reference" action that copies the qualified descriptor for the `target` attribute of injection annotations
- **WIP:** Code completion for `target` attribute of injection annotations
- Possibly other changes I can't remember.

**Planned changes (maybe):**
- Report unnecessary qualified descriptors
- Inspection for method signature of other injection point types + improved quick fixes
- Unit tests

### CODE REVIEW

**Comment by DemonWav** [comment]
Did this really have to be in one giant PR? :S

**Comment by Minecrell** [comment]
@DemonWav Yes, most of this uses shared code, it would be difficult to separate.

**Comment by gabizou** [comment]
@Minecrell the issue with this giant pr is that while it does add a lot of features, it's near impossible to review with limited time. In @DemonWav's defense, his time is fairly limited as is.

**Comment by Minecrell** [comment]
Moved to #123, #124 and #125

**Pull request closed without merging**
