### PR TITLE
Add Mixin debugging support

### PR DESCRIPTION
**Pull request by Minecrell**
Adds support for debugging Mixins the same way you can debug regular Java classes. See https://github.com/SpongePowered/Mixin/pull/155 for an explanation of how it works.

You will still not see the invocation of the injector while debugging, however you can step in the Mixin injector and/or set a breakpoint in a Mixin method.

### Implementation
There are 3 parts that implement the Mixin debugging support for IntelliJ IDEA:

- `MixinRunConfigurationExtension`: Automatically adds the Mixin option (`-Dmixin.sourceDebugExtension=true`) to the VM args when debugging a Mixin module.
- `MixinPositionManager`: Parses the `SourceDebugExtension` added by Mixin and returns the correct Mixin source file while debugging. It will also redirect all breakpoints to the target class so they will work at runtime.
- `MixinDebuggerClassFilterProvider`: Excludes `CallbackInfo` classes from the debugger. Since you don't see the invocation of the injector you need to use Step Into where you expect it to be, the constructor of `CallbackInfo` was just an additional confusing source it jumps to before going to the injector.

### CODE REVIEW

**Comment by DemonWav** [comment]
0/10 short branch name.

**Comment by kashike** [comment]
https://github.com/SpongePowered/Mixin/issues/156

**Comment by gabizou** [comment]
> 0/10 short branch name.

Clearly you haven't seen the branch names on Sponge.

**Comment by Minecrell** [comment]
Changes in Mixin have been pushed, this is ready for merge now.

**Pull request merged**
